/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:b1fd5d13-5eeb-4aaf-b386-d17b9aa86e1a",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_BOCCA2Svi",
    "aws_user_pools_web_client_id": "3htg2b3cp6vomqcabnd18cvfj0",
    "oauth": {}
};


export default awsmobile;
